version: "2"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    container_name: mysqlapp
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat
    volumes:
      - /home/ravendra/volume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d/:ro
      
  app:
    build: ./
    links:
      - db
    container_name: chatbotapp
    ports:
      - "5600:80"


